apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas.mysql }}
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      nodeSelector:
        gpu: nvidia
      containers:
      - name: mysqldb
        image: {{ .Values.images.repository.mysql }}
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_DATABASE
