apiVersion: v1
kind: Service
metadata:
  name: svctododb
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: mysqldb
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: svctodoapp
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: todoapi
  ports:
  - port: 80
    nodePort: 30003
    targetPort: 80
