apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydbpv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /tmp/mysql
    type: DirectoryOrCreate

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydbpvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: slow
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
